### ISSUE TITLE
Meshenger Version 4.3.8. Calling from Android 6.0 to Android 11.0 crashes the app on Android 11.0

### ISSUE THREAD

**Issue by barkoder** [meshenger-app/meshenger-android#141] opened 2024-06-09 13:03 UTC
To reproduce.

0. Install Meshenger 4.2.8 on Android 6.0 device and Android 11.0 device and scan QR codes and Add to Contacts.

1. Notice Green Circle indicator on both devices.

2. Call from Android 6.0 to Android 11.0 .

3. Meshenger on Android 11.0 exits immediately, and the Android 6.0 device throws an error.

**Comment by barkoder** [comment] 2024-06-09 13:11
Also after it errors, when I reopen Meshenger on the Android 11.0 device, the indicator on both the Android 6.0 device and 11.0 device doesn't turn green automatically. I have to open the app switcher on the Android 6.0 device, click on Meshenger again to get the contact indicators on both devices to turn green.

**Comment by barkoder** [comment] 2024-06-09 13:14
Also calling from Android 11.0 to the Android 6.0 device immediately crashes the app on the Android 11.0 device.

Also even after Meshenger crashes on the Android 11.0 device, the contact indicator(for the Android 11.0 device) on the Android 6.0 device continues to stay green, when it should turn red immediately.

**Comment by mwarning** [comment] 2024-06-10 10:58
Hi, are you using a dedicated hotspot / access point? If one of the devices creates a hotspot, then it would be a known problem.

**Comment by barkoder** [comment] 2024-06-10 17:12
I can confirm that hotspot is off on both devices. I'm using my Local Wifi to get the devices to see each other.

**Comment by mwarning** [comment] 2024-07-04 20:42
The current problem is that I do not have an Android 6 phone for testing.

**Comment by iddq** [comment] 2024-07-19 19:12
I got this error on Android 6

Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Optional" on path: DexPathList[[zip file "/data/app/d.d.meshenger-1/base.apk"],nativeLibraryDirectories=[/data/app/d.d.meshenger-1/lib/arm64, /data/app/d.d.meshenger-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]

**Comment by mwarning** [comment] 2024-07-19 20:12
@iddq what Meshenger release is this? Please also try Meshenger 4.3.0 and the 4.3.2-pre (from here https://github.com/meshenger-app/meshenger-android/releases/tag/v4.3.1)

**Comment by iddq** [comment] 2024-07-19 20:57
4.3.1

**Comment by iddq** [comment] 2024-07-19 21:03
4.3.2 is ok. what was the solution? did you remove Optional class?

**Comment by iddq** [comment] 2024-07-19 21:07
Bluetooth: Connection is not working if the hotspot calling the other peer.

**Comment by iddq** [comment] 2024-07-19 21:16
Both devices can successfully establish a connection and make calls regardless of which device initiates the call.

**Comment by mwarning** [comment] 2024-07-20 13:27
@iddq 4.3.1 uses a self compile WebRTC, maybe other build flags are needed.

**Comment by barkoder** [comment] 2024-10-08 06:11
Using 4.3.8 .

For the first time I have the app working and running. I can call between Android 6.0 and 8.1 successfully. Yay!

However calling from Android 11.0 still immediately crashes the app on Android 11.0. Calling from Android 6.0 to 11.0 also crashes the app on Android 11.0 .

No more errors on Android 6.0 like it was in 4.2.8

I'm willing to share any debug logs from the Android 11.0 device via email if that would help, @mwarning .

Thanks.

**Comment by iddq** [comment] 2024-10-08 11:03
please check the log with logcat and send the relevant parts.

**Comment by mwarning** [comment] 2024-10-08 19:27
@barkoder feel free to send the logs to moritzwarning@web.de. But you can also attach them here if that is OK for you.

**Comment by barkoder** [comment] 2024-10-09 05:01
@mwarning

pass for the email I sent you

    ^:*PRPiN)4PgrtO>;t?G1A9k^Tioq0m*l^K;c[lto~0>G8V~%e2Hg2dG2U^7km.TMs\ZeRK<gfG1@@WId|@SuTZeQp8nl+GqR.UM

No Subject

Thanks.

**Comment by mwarning** [comment] 2024-10-09 14:13
@barkoder thank you, I will check the logs later.

**Comment by mwarning** [comment] 2024-10-09 15:21
The problem seems to be that RingtoneManager.getActualDefaultRingtoneUri() calls android.media.RingtoneManager.setRingtonesAsInitValue(), which seem to require android.permission.WRITE_SETTINGS on Samsung devices. Weird.

**Comment by iddq** [comment] 2024-10-09 15:34
Is it in fun initRinging?

**Comment by mwarning** [comment] 2024-10-09 19:08
> Is it in the initRinging function?

yes

**Comment by mwarning** [comment] 2024-10-09 19:18
Looks like this is a known problem for some samsung phones: https://stackoverflow.com/questions/74849517/calling-getactualdefaultringtoneuri-requires-write-settings-permission

**Comment by mwarning** [comment] 2024-10-10 17:06
I pushed a fix that I came up with yesterday. Meshenger should change the default ringtone. As such now a fallback ringtone is used ("Orion" from LineageOS) and a warning is displayed briefly.

**Comment by mwarning** [comment] 2024-10-12 10:44
@barkoder thank you very much for the logs!

This issue might be fixed now with the latest release, please test.

**Comment by barkoder** [comment] 2024-10-16 13:58
@mwarning

It works now. Thank you very much!

**Closed** 2024-10-16 13:58 UTC
