### ISSUE TITLE
Testing the new version of Meshenger Android.

### ISSUE THREAD

**Issue by adicoder95** [meshenger-app/meshenger-android#64] opened 2022-06-29 08:24 UTC
Hey everyone,
I am done with all the modifications  as per GSOC-22.
Now what's left and is really important is to test it as much as possible, on several different devices and so on.
So anyone interested in testing can download the debug apk from this [link].(https://drive.google.com/file/d/1DB7SeBq_MTc9zBfdAM829tIGWN_0qyRV/view?usp=sharing)
If you find any bugs, point those with screenshots if possible.
If you have any feature requests ,point that with a proper reason and how it'll help our target audience.
The source codes can be found on GSOC-22 branch.
Feedbacks are highly appreciated.
Thankyou.

**Comment by opusforlife2** [comment] 2022-07-03 15:33
Oh, sorry. I missed this and just replied in the other issue. Downloading now.

Rather than (or in addition to) a GDrive link, directly attaching the APK to your OP would be great.

Also, maybe change the app and package name to Meshenger Debug or Test for this APK?

**Comment by opusforlife2** [comment] 2022-07-04 06:58
BTW do you have a summarised changelog or release notes anywhere? It would help in testing.

**Comment by opusforlife2** [comment] 2022-07-04 19:40
Right off the bat, opening the test app shows you a name dialog, and then another one saying "No Wifi card found, setup later?" even if Wifi is on and Internet is working. Tapping on "Ok" does nothing but show the dialog again.

If you tap on "skip", you get a mic permission prompt, but another window seems to open behind it (you see an animation giving this impression).

In advanced settings, I can see several MACs and IPs, which means the app can indeed detect that Wifi is on. But then that "card not found" dialog shouldn't have shown up.

What does "Default" do in the Video Resolutions menu? Automatically choose a resolution based on network speed? If so, is this a one-time thing? Or does it dynamically adjust resolution based on periodic network speed detection?

Maybe the app could detect the system theme and apply it on first startup.

Why is there an Import/Export Path text field? Tapping on the Import/Export buttons already takes you to the SAF file chooser, so that Path field seems redundant. It also doesn't get populated with your chosen path using the buttons.

The floating action buttons should probably have tooltips.

The About page could have a link to this Github repo, the issues tab, the releases tab for changelogs, etc.

**Comment by opusforlife2** [comment] 2022-08-27 16:01
@adicoder95 ?

**Comment by mwarning** [comment] 2022-08-27 16:07
hi @opusforlife2, sorry for the silence. We have decided to build on top of the master branch instead of the development branch and then integrate code from the development branch to the master branch.

The current code is here: https://github.com/meshenger-app/meshenger-android/tree/GSOC-22_new

@opusforlife2 please have a look, thank you.
@adicoder95 feedback is valuable. Please have a look and see if we can address the issues.

**Comment by opusforlife2** [comment] 2022-08-27 16:12
That's perfectly fine, I just didn't see any acknowledgement so didn't know if my feedback was being taken into account. Please don't hesitate in pinging me when a new debug build needs testing.

**Comment by adicoder95** [comment] 2022-08-27 17:05
@opusforlife2 actually I was working towards the newer version of it, sorry about not responding as I got a bit stuck and forgot about that. Yes I did went through what you said then and tried to resolve the same.
Here is the debug apk of the latest Meshenger version 4.0.0
https://drive.google.com/file/d/1ARogJkEMHEiP226GYuSTUrOT-ZOrKdLf/view?usp=sharing
Thanks.

**Comment by opusforlife2** [comment] 2022-09-01 20:08
- I could successfully add contacts.
- But calls don't work. It says "Error".
- After ending the call, the proximity sensor stays active. Need to swipe away the app to deactivate it.
- Small screens still have layout issues.
- Toggling night mode on and off takes you back to the main app, but on an Android 8 phone, it crashes the app instead.

**Comment by adicoder95** [comment] 2022-09-01 20:35
@opusforlife2 you were connected to the same wifi on both device and still it showed an error??
Was the app open in both device as the apk I shared doesn't has the background call receiving thing active.

**Comment by opusforlife2** [comment] 2022-09-01 20:36
Yep. Same wifi. Both apps in foreground.

**Comment by adicoder95** [comment] 2022-09-01 20:38
can you possibly send a video so I can have a look,
Did you see the address management screen and made sure correct address is selected?

**Comment by adicoder95** [comment] 2022-09-01 20:44
@opusforlife2 I just made a new commit with many fixes. I am attaching a link to the latest apk. Do check and let me know if the error still exists.
https://we.tl/t-99jMqik4h1

**Comment by opusforlife2** [comment] 2022-09-01 20:58
Just opened the app after installing, and instead of the main screen, it took me to the "Display over other apps" system settings.

**Comment by adicoder95** [comment] 2022-09-02 06:32
Yes we need the display over other permission to make the app receive calls in the background.
Exactly the red dot means that the device is not ready to make a call.
I need to look about the proximity sensor, am not really sure about how we can fix it.

**Comment by opusforlife2** [comment] 2022-09-03 15:30
>Yes we need the display over other permission to make the app receive calls in the background.

That's not the case with other VoIP-capable apps. Neither Telegram nor Element require it, for example. Just a permanent notification is enough.

**Comment by opusforlife2** [comment] 2022-09-03 15:44
Tried with another phone.
- Both successfully showed green dots.
- Calls were successfully established.
- But no voice could be heard on either device.
- Trying to turn on video caused a crash:

```
FATAL EXCEPTION: main
Process: d.d.meshenger.test, PID: 5884
java.lang.NullPointerException
	at d.d.meshenger.RTCCall.setVideoEnabled(RTCCall.kt:74)
	at d.d.meshenger.CallActivity.switchVideoEnabled(CallActivity.kt:245)
	at d.d.meshenger.CallActivity.onCreate$lambda-4(CallActivity.kt:186)
	at d.d.meshenger.CallActivity.lambda$tWlTn7dxVRpo580i4CpygWmhtds(Unknown Source:0)
	at d.d.meshenger.-$$Lambda$CallActivity$tWlTn7dxVRpo580i4CpygWmhtds.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by mwarning** [comment] 2022-09-03 16:56
@opusforlife2 I also experienced crashes. But every time I try to reproduce it to get a stack trace, it works.

**Comment by opusforlife2** [comment] 2022-09-03 16:57
@mwarning Scoop on F-Droid is amazing for such scenarios, if you have root or adb access.

**Comment by mwarning** [comment] 2022-09-03 17:15
I installed scoop. Now I need a crash :D

**Comment by opusforlife2** [comment] 2022-09-17 19:57
Update:
- Got calls to work successfully between two phones! Woohoo!
- The app only shows the other user's video. It should also show your own video.
- Now it seems like the proximity sensor problem only occurs for failed/incomplete/faulty calls. For successful calls, the sensor is correctly disengaged when the call ends.
- If you don't have the app open on a device and it receives a call, picking and ending that call still leaves the call screen available in Recent Apps. If you tap that, you get a ghost incoming call. If you accept it, it shows an error. If you reject it, the app correctly opens its main screen.

**Comment by mwarning** [comment] 2022-10-08 21:56
@opusforlife2 feel free to test again. The issue you have encountered are still present. But that is for the next release.

**Comment by adicoder95** [comment] 2022-10-09 06:29
Nice @mwarning I didn't found any crashes in my android 12 devices.

**Comment by mwarning** [comment] 2022-10-09 09:28
@adicoder95 yes, no crashes. But what about bugs?

**Comment by opusforlife2** [comment] 2022-10-09 12:37
@mwarning I'll need a test APK for that.

**Comment by mwarning** [comment] 2022-10-09 14:34
I guess it is better to make a release and then a bugfix release to address any issues we encounter. It has been long enough. :-)

**Comment by opusforlife2** [comment] 2022-10-09 16:18
Testing release version 4.0.0 (🎉):
- Calls work perfectly between Android 12 and 10.
- If the app crashes for any reason while video is active, A12 shows the camera still being used (the green dot). Making another call and then cancelling it properly shuts off the camera too. This sounds like the same problem with the proximity sensor I mentioned above.
- For Android 8, the call gets established, but no sound or video goes through, for either participant.

**Comment by mwarning** [comment] 2022-10-09 16:22
Ok, thank you. I will take a look next week.

**Comment by mwarning** [comment] 2022-10-26 22:31
@opusforlife2 let's hope the bug is fixed now. Please create a new issue if it appears again.

**Closed by mwarning** 2022-10-26 22:31 UTC

**Comment by opusforlife2** [comment] 2022-10-26 22:38
No problem. Please also look at the other issues I've mentioned here for future versions.

**Comment by opusforlife2** [comment] 2022-10-29 19:37
A very small thing: since Meshenger has a permanent notification running, you could remove the time-ago from the notification header.

**Comment by mwarning** [comment] 2022-10-29 20:29
@opusforlife2 thank you for the feedback, done here https://github.com/meshenger-app/meshenger-android/commit/2cc3ef131856db16b6271392b095d58396c0b1ef
