### ISSUE TITLE
[Design] Create graphical assets for play store launch.

### ISSUE THREAD

**Issue by adicoder95** [meshenger-app/meshenger-android#82] opened 2022-10-14 07:09 UTC
We need screenshots of Tablet for the app listing on the play store.

**Comment by springdaysenpai** [comment] 2022-12-22 11:31
Hey, @adicoder95 if this is an open source project and the issue is still open, I would love to work on this! I am new to open source but i can definitely help you out with designs and color palettes for the app.

**Comment by adicoder95** [comment] 2022-12-22 11:47
sure @straw-hat-senpai you can do it

**Comment by straw-hat-senpai** [comment] 2022-12-22 13:09
Okay great! Could you clarify this once, i have to submit a screenshot of tablet view of the app right?
Also could i do some sample work for the design and UI of the app if that is something that needs to be worked on?

**Comment by mwarning** [comment] 2022-12-22 14:00
Hi @straw-hat-senpai, as @adicoder95 already said. the task is still open.
What we need is a tablet screenshot that we can use for the Play store and whatevery is missing there.

**Comment by straw-hat-senpai** [comment] 2022-12-22 16:23
Hey @mwarning, here is a sample of tablet view of the app landing page. Please confirm if this is what is required!
![logo_4 0 4 tablet](https://user-images.githubusercontent.com/91172425/209177904-5936620a-a961-4e59-83ba-6206599fb1ec.png)

**Comment by adicoder95** [comment] 2022-12-22 17:52
yes @straw-hat-senpai  this is exactly what we need but vertically so the full screen fits
It would be used for play store listings

**Comment by mwarning** [comment] 2022-12-22 19:15
I just checked in the play store:
* Feature graphic "Your feature graphic must be a PNG or JPEG, up to 15 MB, and 1,024 px by 500 px"
** we have a graphic, but maybe we can find something better
* 7-inch tablet screenshot "Upload up to eight 7-inch tablet screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 320 px and 3,840 px"
** we use a dummy here (startup screen)
* 10-inch tablet screenshots "Upload up to eight 10-inch tablet screenshots. Screenshots must be PNG or JPEG, up to 8 MB each, 16:9 or 9:16 aspect ratio, with each side between 1,080 px and 7,680 px"
** we use a dummy here (startup screen)

**Comment by straw-hat-senpai** [comment] 2022-12-22 19:31
I have completed all samples of tablet view screenshots, they might be a little bit different than these specifications but i can adjust them accordingly as well. Could you please review it once before i change the pixels and aspect ratios according to play store requirements.
![address_management_4 0 4 tablet](https://user-images.githubusercontent.com/91172425/209212099-50e57237-dd44-47e7-9249-df7e58bc64bd.png)
![contacts_4 0 4 tablet](https://user-images.githubusercontent.com/91172425/209212107-1f18d4d8-6cb2-4493-bb45-662fd75a29cc.png)
![hello_4 0 4 tablet](https://user-images.githubusercontent.com/91172425/209212111-5750e833-72b8-4c33-9a4c-3a9b3b8b58f8.png)
![logo_4 0 4 tablet](https://user-images.githubusercontent.com/91172425/209212116-57ef4186-4fd0-4d56-9d2f-8793c6b41a74.png)
![qrcode_4 0 4 tablet](https://user-images.githubusercontent.com/91172425/209212120-75a971d9-7dcb-48c7-b78b-d482b44bc755.png)
![ringing_4 0 4 tablet](https://user-images.githubusercontent.com/91172425/209212130-023cd560-134e-448f-aa57-7f33a20d2260.png)
![settings_4 0 4 tablet](https://user-images.githubusercontent.com/91172425/209212136-fd38827e-0397-4e36-b611-aac1a8c348d2.png)
![video_call_4 0 4 tablet](https://user-images.githubusercontent.com/91172425/209212142-c7b9ce00-53ee-4af3-b8ff-fcd87c38222a.png)

**Comment by straw-hat-senpai** [comment] 2022-12-22 19:36
I have completed all tablet view screenshots but they need to be adjusted according to these specifications. Could you please review them once before i make the aspect ratio changes and other modifications to them.
[https://drive.google.com/drive/folders/1mAqXbS407LSVcfLjEBsk0nhdU_mZaWKC?usp=sharing](url)

**Comment by straw-hat-senpai** [comment] 2022-12-22 19:46
Also i had a question, Is the app responsive yet?

**Comment by mwarning** [comment] 2022-12-22 20:41
@straw-hat-senpai thank you. I just noticed that the tablet screenshots can be removed afterwards. Maybe we then do not need these screenshorts, except for a better feature graphic.
The is not responsive and has never been tested on a tablet (to my knowledge).

**Comment by straw-hat-senpai** [comment] 2022-12-23 05:56
Okay then, should i work on a better feature graphic?

**Comment by straw-hat-senpai** [comment] 2022-12-23 06:58
@mwarning @adicoder95 Here are some samples for the feature graphic! Let me know if any of these is usable or need any modifications!
https://drive.google.com/drive/folders/1N79TNt5LZ1RTa4mK5MNCe1IpFZ_XCAZ5?usp=sharing

**Comment by mwarning** [comment] 2022-12-23 11:07
@straw-hat-senpai looks like a good start. Give me some time to gather feedback.

**Comment by straw-hat-senpai** [comment] 2022-12-23 12:29
Okay!

**Comment by mwarning** [comment] 2022-12-24 21:05
The font has a grafitti style and the background an old industrial area style. While for Meshenger I hope for something more professional looking.

Btw. I also think about rebranding Meshenger. Since the name does not fit what it does (it is not a messenger, not does it mesh :P). And red/black is not a good color scheme. This e.g. looks better: https://play.google.com/store/apps/details?id=d.d.meshenger (it's is actually Meshenger under to hood)

**Comment by straw-hat-coder** [comment] 2022-12-25 09:25
Yes i agree @mwarning , actually the samples were created keeping in mind the name 'meshenger' which would include a mesh design. But i was also thinking of a new color scheme and font style, something which looks more professional as you said. The Wicall app's UI is somewhat like the design we're looking for i think. I'll put together some modern & minimal color palettes for your review and work on it accordingly!

**Comment by mwarning** [comment] 2022-12-25 09:59
@straw-hat-coder that would be nice. Maybe we can find a style direction that appeals a broader audience.

**Comment by straw-hat-coder** [comment] 2022-12-28 13:42
Hi, @mwarning here is a link to the sample designs i created. https://www.figma.com/file/pUCWq05LwH0uHxHHAl8PzK/MESHENGER-UI-DESIGN?node-id=6%3A475&t=FdZ73cl4O6v5Ei4e-1
If required we can also change the color palette too. Here are some suggestions for the color schemes. 
![Color palettes for meshenger](https://user-images.githubusercontent.com/91172425/209821133-2fe7231b-6188-4448-abb8-6c59a6469d60.png)

**Comment by mwarning** [comment] 2023-01-09 19:17
@straw-hat-coder what kind of feedback to would you need? Do you mean the previous zip you linked? Btw, the feature graphic does not seem to appear in the playstore.  I do not have any timeline about the new color scheme.

**Comment by straw-hat-coder** [comment] 2023-02-10 13:36
@mwarning Is there a slack channel for discussions and feedback for the team?
Here's a link to feature graphic samples. Should i do a PR to update the feature graphic for the next play store release?
https://drive.google.com/drive/folders/1N79TNt5LZ1RTa4mK5MNCe1IpFZ_XCAZ5

**Comment by mwarning** [comment] 2023-02-13 17:54
Hi @straw-hat-coder, there slack channel. But you can reach me via Element (mwarning42 on matrix.org).
The current problem is that the feature graphic do not really fit the style and font of the Meshenger app. Maybe we can iterate different designs?

**Comment by straw-hat-coder** [comment] 2023-02-15 09:38
Thank you for the response. I will gather some more design options for the feature graphic. Also, are there any UI design updates to be worked on? If yes, i would like to work on the same. I will include the current font style of the app in the feature graphic samples.

**Comment by mwarning** [comment] 2023-02-15 18:04
Hi, there are no UI design changes being worked on. Feel free to work on it.

**Comment by mwarning** [comment] 2023-05-30 17:59
Let's close this ticket for now revisit the play store assets when the design of the app changes.

**Closed by mwarning** 2023-05-30 17:59 UTC
