### ISSUE TITLE
Feature request: Add support for VPN

### ISSUE THREAD

**Issue by olofpp** [meshenger-app/meshenger-android#54] opened 2021-08-14 11:53 UTC
Meshenger doesn't find tun0 device and there for doesn't work over VPN. 
It would be really nice if users could connect to the same VPN and connect with each other.

**Comment by mwarning** [comment] 2021-08-14 15:01
Absolutely, I agree. This is fixed in the current reworked code in the development branch. The problem is, that the code is buggy in other respect and not ready for release and I am hold up with other projects :(

**Comment by adicoder95** [comment] 2022-06-26 18:21
I would look into it and try to integrate in the GSOC-22 branch.

**Comment by mwarning** [comment] 2022-10-09 16:28
This should be fixed in the latest release.

**Closed by mwarning** 2022-10-09 16:28 UTC
