### ISSUE TITLE
Volume issue after a call has been terminated

### ISSUE THREAD

**Issue by mvglasow** [meshenger-app/meshenger-android#20] opened 2019-09-19 21:36 UTC
### Steps to reproduce

1. Install Meshenger on two devices and exchange contacts.
2. Establish a call between the devices, verify everything works, then hang up.
3. Call again and re-run the tests.

### Expected results

Step 3 works just as step 2 did.

### Actual results

Step 2 works, but in step 3 the ring volume of the called device is so low that it is barely audible. The same goes for in-call volume on one or both ends (I got varying results here.)

After killing and restarting Meshenger on both devices, ringer and in-call volume are normal again for the first call.

### Additional information

Unfortunately I did not keep track of whether the calling device was the same in both step 2 and 3, or which side hung up. This would need some further tests.

### Versions used

Meshenger 2.1.0 from F-Droid

Device 1: OnePlus One running LineageOS 15.1-20190226-NIGHTLY-bacon

Device 2: Nexus S running Cyanogenmod 11-20141112-SNAPSHOT-M12-crespo

**Comment by mwarning** [comment] 2019-09-20 22:38
No idea why this is happening. Any pull requests are welcome.

**Comment by mwarning** [comment] 2019-09-22 21:53
I sometimes experience that the "Unknown Caller" (feature in 3.0.0) does not get through.
3.0.1 will be in froid next week. It would be nice if you could give it a check if the situation has changed.

**Comment by mvglasow** [comment] 2019-10-11 17:55
Just upgraded and there is now a different issue:

* Launch Meshenger on device 1, device 2 is shown as offline (obviously).
* Launch Meshenger on device 2, it will show the spinning donut next to device 1 forever. Device 1 keeps reporting device 2 as offline.
* Restart Meshenger on device 1, now there is a spinning donut next to device 2 as well.
* Try to make a call (in either direction), call setup fails with the message “Error”

Something seems to get stuck when the other device is online; thus I cannot test calls with this version.

**Comment by mwarning** [comment] 2019-10-11 20:18
I think the problem is that a change of online status does not update the user interface (but it will be updated if you put Meshenger into background and bring it back into foreground).

Anyway, you should be able to call the other phone even when it is shown as offline. This is mostly a display issue.

**Comment by mvglasow** [comment] 2019-10-11 20:35
Yes, the “display not updating” issue has been around before. Even so, if I call a phone shown as offline (but which has come online since), I get the same behavior—Meshenger tries to set up a call but then shows “Error”. Somehow device discovery gets stuck somewhere.

**Comment by mwarning** [comment] 2019-10-11 20:48
hm,  ok. Did you exchange the qr-codes with the MAC address configured? And are you connected to the same wifi router? (using one phone as wifi hotspot does not work in both direction - nasty Android behavior..)

**Comment by mvglasow** [comment] 2019-10-11 20:51
Yes and yes, same setup I used with the previous version and with which I was able to establish a call there. I simply upgraded and lost the ability to make calls after that, otherwise same environment configuration as before.

**Comment by mwarning** [comment] 2019-10-11 21:47
I would love to be able to reproduce the error. But it works for me...

**Comment by mwarning** [comment] 2022-12-24 20:44
Please open a new issue if the problem persists.

**Closed by mwarning** 2022-12-24 20:44 UTC
Labels: bug
