### ISSUE TITLE
bug Connection failed

### ISSUE THREAD

**Issue by SunDaSora** [meshenger-app/meshenger-android#89] opened 2022-12-04 03:30 UTC
The connection failure problem exists in both the latest versions, 403 and 404. But the 402 version is normal。
The 402 version can be called, but the 403 and 404 versions cannot be called.
 The 403 version prompts an error, and the 404 version prompts are rejected.

**Comment by SunDaSora** [comment] 2022-12-04 03:32
You can use version 402 to call version 402.
And you can use version 403 and version 404 to call version 402.
But you can't use the 402 version. Call 403 and 404.

**Comment by mwarning** [comment] 2022-12-04 10:12
That would be weird, I will need to run some tests.

**Comment by mwarning** [comment] 2022-12-05 21:40
I can confirm that it is not possible to call 4.0.4 to 4.0.2.
The reason seems to be a bug in 4.0.2:

```
2022-12-05 22:35:24.486 16125-17552 org.we...gging d.d.meshenger     E  SurfaceTextureHelper: CaptureThread create failure
2022-12-05 22:35:24.486 16125-17552 org.we...gging d.d.meshenger     E  SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003
2022-12-05 22:35:24.487 16125-17552 org.we...gging d.d.meshenger     E  SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003
                                                                        	at org.webrtc.EglBase14.createEglContext(EglBase14.java:274)
                                                                        	at org.webrtc.EglBase14.<init>(EglBase14.java:71)
                                                                        	at org.webrtc.EglBase.create(EglBase.java:91)
                                                                        	at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:119)
                                                                        	at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:34)
                                                                        	at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:68)
                                                                        	at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:63)
                                                                        	at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
                                                                        	at android.os.Handler.handleCallback(Handler.java:938)
                                                                        	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                        	at android.os.Looper.loopOnce(Looper.java:201)
                                                                        	at android.os.Looper.loop(Looper.java:288)
                                                                        	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by SunDaSora** [comment] 2022-12-06 04:29
Okay, but I still stand by my opinion. I looked for more equipment to test. Including redmi k40, Huawei enjoy 9, redmi 5 plus, xiaoxin pad.
When I use all 404 versions, only Huawei Enjoyment 9 can be called by other devices.
When I used all 402, only Xiaoxin pad could not call Huawei Enjoyment 9, and all other devices were normal.
Picture 1 is the 404 version and picture 2 is the 402 version.
![P_20221206_120915](https://user-images.githubusercontent.com/49709661/205814879-2b1233b7-4862-4512-9e67-08ca8b874479.jpg)
![P_20221206_121924](https://user-images.githubusercontent.com/49709661/205814919-88d5dc2c-da5f-4054-a37f-88fa9c09f8b6.jpg)

**Comment by mwarning** [comment] 2022-12-06 21:08
HI @SunDaSora, thank you very much for such extensive testing. I have two devices for testing, one Android 12 and an Android 8.1 (both LineageOS).
This whole issue is probably some undefined behavior that can be resolved by making the code more robust and then analysing the remaining issues.

**Comment by SunDaSora** [comment] 2022-12-07 00:32
Okay, I'm not asking you to do anything to the old version, just to find that the new version has some problems that don't exist in the old version. I hope it helps you.
Of course, I am not a professional, and I can only see the surface of some problems.
Of course, the problem may not come from the application itself, or it may come from my home network, but I can't confirm it at present, because I'm not professional.
PS: The messages you see are translated by translation software, and there may be errors.

**Comment by mwarning** [comment] 2022-12-07 06:41
> Okay, I'm not asking you to do anything to the old version, just to find that the new version has some problems that don't exist in the old version. I hope it helps you. Of course, I am not a professional, and I can only see the surface of some problems. Of course, the problem may not come from the application itself, or it may come from my home network, but I can't confirm it at present, because I'm not professional.
The feedback certainly helps and I am grateful. Let's see if the bug can be found and fixed.

> PS: The messages you see are translated by translation software, and there may be errors.
It's fine. I can understand you. :-)

**Comment by RunningDroid** [comment] 2022-12-14 02:13
I have this issue as well; my OnePlus 7 Pro (Android 11) can call my Samsung S7 (Android 8.0) but my Samsung S7 can't call my OnePlus 7 Pro.
I captured some logcat logs from my Samsung S7 while reproducing this bug but I don't know if they'll be useful:
[adb.log](https://github.com/meshenger-app/meshenger-android/files/10223640/adb.log)

**Comment by mwarning** [comment] 2022-12-14 17:40
@RunningDroid hi, thank you for the report. The logs for release builds are very sparse. I will offer a debug build for the next release.

**Comment by mwarning** [comment] 2022-12-20 23:02
I just published a new release and hope the situation now improves a bit.
@RunningDroid there now also a debug build with lot's of debug output enabled.

**Comment by RunningDroid** [comment] 2022-12-21 05:20
It still seems to be happening, unfortunately.
Here's the new logcat with my Samsung S7 (Meshenger 4.0.5 debug) calling my OnePlus 7 Pro (Meshenger 4.0.4) : [adb.log](https://github.com/meshenger-app/meshenger-android/files/10274577/adb.log)

**Comment by mwarning** [comment] 2022-12-22 13:56
@RunningDroid thank you for the logs. There I see the following lines:

```
2-20 23:38:51.205 18148 18170 D MainService: new incoming connection
12-20 23:38:51.209 18148 18492 D RTCCall$Companion: incoming peerConnection from /fe80::e62c:8ba2:46b9:3a8d%wlan0:49958
12-20 23:38:51.210 18148 18493 D RTCCall$Companion: createIncomingCallInternal
12-20 23:38:51.213 18148 18493 D RTCCall$Companion: incoming peerConnection from /fe80::e62c:8ba2:46b9:3a8d%wlan0:49960
12-20 23:38:51.215 18148 18492 D RTCCall$Companion: decryption failed
12-20 23:38:51.216 18148 18493 D RTCCall$Companion: decryption failed
```

The looks like the keys of either sender or received have changes (probably a reinstall I would assume).
You could try a clean install and also both Meshenger 4.0.5 versions. It is unlikely that I will have time to fix backwards compatibility if it was broken by accident.

**Comment by mwarning** [comment] 2022-12-24 11:46
This backwards compatibility issue will not be resolved. Closing this issue.

**Closed by mwarning** 2022-12-24 11:46 UTC
